### ISSUE TITLE
Add a progress indicator in the taskbar

### ISSUE THREAD

**Issue by KaiDevrim** [Mowjoh/Quasar#3]
I noticed that while transferring my mods to my switch I had to keep on opening the app to see if it finished the transfer. I know that there is a way to add a progress indicated like the following for bandizip.
![image](https://user-images.githubusercontent.com/36937771/96507303-d279bb00-120d-11eb-8e5b-939db379a6f8.png)

Currently I think having it for the mod transfer would be good.

**Comment by Mowjoh** [comment]
It was added before, the whole "rewrite the app" got rid of it temporarily, don't worry about it, it'll return !
