### ISSUE TITLE
change download location?

### ISSUE THREAD

**Issue by kirbysblockball** [Mowjoh/Quasar#4]
heya, is it possible to change the folder that mods will download to? i don't have much space on my c:\ drive, and i imagine other people would have a similar problem

**Comment by Mowjoh** [comment]
Yup, it is, although in a complicated manner for now. 
What you have to do is close Quasar, 
Open the file in 
C:\Users\[YourUsername]\AppData\Local\Quasar\Quasar.exe_[random characters]\[version number]\user.config

(yeah sorry for the long path but that's where config go by default.)

You'll see a line that says 
<setting name="DefaultDir" serializeAs="String">
                <value>C:\Users\[YourUsername]\Documents\Quasar</value>
</setting>

Change that value to the selected location you want, 

Move the Quasar folder that's currently in your "My Documents Folder" to that location, and it should work.

There'll be an option to make that easier later, but this workaround should be working, let me know if it doesn't

**Comment by Mowjoh** [comment]
The upcoming 2.0 includes a first start location change, but there's also an option in the settings tab for that
