### ISSUE TITLE
Even upon building latest Steve does not appear

### ISSUE THREAD

**Issue by GarnetSunset** [Mowjoh/Quasar#5]
Built the latest version and Steve mods don't appear in the "fighters" menu, just a heads up, I saw you added cursory fixes, but sitll no luck

**Comment by MasterDriverRex** [comment]
Yeah, this program desperately needs an update by this point; we've now got Steve, Sephiroth and Mythra/Pyra, all of whom do not appear in Quasar's fighter list.

Really, as it stands, this program is less than ideal. If only someone had the skills to fork it and add all the new stuff in...

**Comment by megamanzerobasslink** [comment]
He's working on it https://www.youtube.com/watch?v=cw-RdS7hydU

**Comment by MasterDriverRex** [comment]
Has the author stated that anywhere? Because, well, it has been roughly seven months (Sep, Oct, Nov, Dec, Jan, Feb, and now Mar) since the last update, which is...kind of an issue...

**Comment by Mowjoh** [comment]
I'll state that here, I'm working on it. I'm not just bringing characters to Quasar. There's more to it. It's been rough lately so I didn't update it in a long time but rest assured that it is. Sorry for the wait.

**Comment by megamanzerobasslink** [comment]
Don't pull a Yandev please

**Comment by MasterDriverRex** [comment]
Sure, thanks!

And, upon checking the branches, I did find the [Develop branch](https://github.com/Mowjoh/Quasar/tree/develop), which was last updated fairly recently (23 Jan), so there is some proof you're working on it.

**Comment by Mowjoh** [comment]
Basically, i've done a visual redesign, alot of improvements left and right, a new data storage design, and well, i'm also making sure that you'll be able to keep all your mods from the previous to the next data models, with the least amount of loss. It's complicated but I'm working through that. ![unknown.png](https://user-images.githubusercontent.com/12461420/111088034-6df52a80-8525-11eb-810c-8a7f531d09b9.png)

Here's a preview of the new design (old screencap I had laying around) so it won't be exactly that but it's pretty close to my local latest build.

**Comment by Mowjoh** [comment]
I've worked alot
It's just that I want to polish that 2.0 and not rush the release and then have to face unintended issues.

**Comment by MasterDriverRex** [comment]
@Mowjoh One more thing...might want to consider updating the Wiki images when you're done. It's got the incorrect tab names now...

**Comment by Mowjoh** [comment]
Will do all that for 2.0

**Comment by Mowjoh** [comment]
I'm closing this because 2.0 is near and will include the latest game data for use
