### ISSUE TITLE
several SSBU mods cannot be add to workspace

### ISSUE THREAD

**Issue by zany130** [Mowjoh/Quasar#6]
like the title says I am unable to add certain mods to a workspace.

AirDashing

boss battles over classic mode [Revamped]

DashDancing+ (1 of 2)  (DashDancing+ Expansion Pak Can be added, however)

Uncensored Spirits Pack

v99 Main Menu

Zwei (RWBY) over Nintendog Assist Trophy

**Comment by Mowjoh** [comment]
This is a detection issue. The 2.0 will show a new detection state to indicate this mod cannot be currently used by Quasar. Please let me know about them so I can add their type compatibility to Quasar. Thanks !

**Comment by RogueOwl** [comment]
I'm having issues loading mods in the UI and animation categories, plus some other mods don't have their CSS icons properly installed
